### ISSUE TITLE
Ability to increase the font size of the open files text in the side panel

### ISSUE THREAD

**Issue by mr-Qberry** [eablokker/nova-tabs-sidebar#16]
Please could you add an option to increase the font size of the open files name text. I'm having difficulty comfortably reading each file name in the panel. Being able to increase the text size to a custom level would assist me greatly. Otherwise this is a brilliant extension which has added a feature I've been missing since switching to Nova from Expresso.

**Comment by eablokker** [comment]
I'm sorry but it's not possible. The Nova extension API doesn't give me the ability to do that. I have been requesting for years more abilities for the sidebar component, but they have never added any new features. Despite the fact that you can change the font size in their built-in files sidebar, they do not provide the option to do that in a sidebar extension.

I wish Espresso wasn't abandoned :(
