### ISSUE TITLE
"Group by Ancestor" option

### ISSUE THREAD

**Issue by ashur** [eablokker/nova-tabs-sidebar#4]
## Summary

Similar to the extension's **Group By Kind** option and Nova's built-in **Move All Tabs With Ancestor** feature, I'd love the ability to group open files by their parent folder.

## Configuration

* **Version** — 1.5.2
* **Nova** — 9.6

## Severity

* Enhancement

## Notes

This is a really handy extension, thanks so much for working on it!

**Comment by eablokker** [comment]
This is on my todo list. I'll bump up the priority.

**Comment by eablokker** [comment]
@ashur I've just released a new version of the extension that adds a group by folder option. It displays the entire folder hierarchy of any open files.

**Comment by ashur** [comment]
@eablokker This looks really great, excited to start using it! 💫
