### ISSUE TITLE
"Could not find Git repo in current workspace... "

### ISSUE THREAD

**Issue by GaryREM** [eablokker/nova-tabs-sidebar#6]
Extension Console shows "Could not find Git repo in current workspace The process did not respond in a timely manner." for Tabs extension. This message appears when extension is restarted.

Have git 2.39 installed and .git folder is in workspace root.

**Comment by eablokker** [comment]
Are you not seeing git status icons next to your open (modified) files in the tabs sidebar?

The extension uses the `git rev-parse --show-toplevel` command to find the root folder of your repo. If that command returns an error, then the extension prints that message in the console. If you run that in terminal in your project folder, what do you see?

**Comment by GaryREM** [comment]
Hmm... No error now! Also the annoying filetype warnings are also gone. Finally, the git status on modified files is showing up.

So everything is working!! Thanks. (new version of extension and Nova...)
