### ISSUE TITLE
Blinks every time new file is being opened

### ISSUE THREAD

**Issue by nesvet** [eablokker/nova-tabs-sidebar#8]
Hi! Thanks for this useful extension!

Btw it blinks on every refresh (if it has "Group By Kind" enabled, it runs unfold animation on every group). Is there way to manage this little thing?

**Comment by eablokker** [comment]
I was finally able to recreate this. I didn't know what you meant. It happens when you create a new untitled, unsaved document and then start typing in it.

If you save the document, close the tab, then reopen the document it is fixed.

I will try to fix the issue when the document is new.

**Comment by eablokker** [comment]
I think I've fixed it in the latest update
